# Problem 1

In [2]:
import numpy as np
matrix = np.random.randint(0, 11, size=(5))
print(matrix)
print(matrix.shape)
print(matrix.reshape(5,1))
matrix.ndim


[6 8 4 2 4]
(5,)
[[6]
 [8]
 [4]
 [2]
 [4]]


1

# Problem 2

In [4]:
matrix = np.arange(1,11)
tek_sayı = matrix[matrix%2 !=0]
# farklı bir yol
matrix2 = np.arange(1,11,2)
matrix,b,c = np.split(tek_sayı,[2,4])
print(f"{matrix} / {b} / {c}")
yenimatrix = np.concatenate((matrix,b,c))
print(yenimatrix)


[1 3] / [5 7] / [9]
[1 3 5 7 9]


# Problem 3

In [5]:
matrix = np.arange(5, 101, 2)
np.random.shuffle(matrix)
matrix = matrix[10:20].reshape(5, 2) 
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

[[69 43]
 [27 97]
 [59 79]
 [71 81]
 [83 53]]
2
(5, 2)
10
int32
