# Problem 1 

In [2]:
import numpy as np
liste = np.array([1,2,3,4,5])
print(np.sort(liste))

[1 2 3 4 5]


# Problem 2

In [4]:

liste2 = np.array([10,15,30,45,60])
list3 = np.arange(5,15)
print(list3)
liste4 = np.arange(50,100,5)
print(liste4)
liste5 = np.zeros(10)
print(liste5)
print(np.ones(10))
liste6 = np.linspace(0,100,5)
print(liste6)
liste7 = np.random.randint(10,30, size=5)
print(liste7)
liste8 = np.random.uniform(-1,1, size=10)
print(liste8)
liste9 = np.random.randint(10,50, size=(3,5))
print(liste9)
print(np.sum(liste9, axis=0))
print(np.sum(liste9, axis=-1))
print(f"{np.max(liste9)} {np.min(liste9)} {np.mean(liste9)}")
print(liste9.argmax())
liste10 = np.random.randint(10,20 ,size=8)
print(liste10[:3])
print(liste10[::-1])
print(liste9[0])
print(liste9[1,2])
print(liste9[:,0])
print(liste9**2)
liste11 = np.random.randint(-50,50,size=(3,5))
pozitifcift= liste11[(liste11 >0 ) & (liste11 % 2 == 0)]
print(pozitifcift)


[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 27 14 12 18]
[ 0.25138544 -0.30155039 -0.44431153  0.68550771 -0.6557497  -0.67923393
  0.60475672 -0.90997715  0.96896077  0.7773612 ]
[[43 32 46 38 32]
 [48 38 30 22 18]
 [42 21 46 43 27]]
[133  91 122 103  77]
[191 156 179]
48 18 35.06666666666667
5
[13 10 11]
[19 11 11 12 17 11 10 13]
[43 32 46 38 32]
30
[43 48 42]
[[1849 1024 2116 1444 1024]
 [2304 1444  900  484  324]
 [1764  441 2116 1849  729]]
[10 36 14 40]
